# Generated by Django 5.2.17 on 2026-10-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(db_index=True, max_length=20)),
                ('request_id', models.CharField(max_length=64)),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'request',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('env', 'request_id'), name='unique_request_per_env')],
            },
        ),
        migrations.CreateModel(
            name='RequestBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='collector.request')),
            ],
            options={
                'db_table': 'request_body',
            },
        ),
    ]
